---
- name: this is tomcat ansible playbook
  hosts: all
  become_user: root
  become: true
  
  tasks:
    - name: deploy war file on tomcat server
      copy: src=/webapp/target/webapp.war dest=/opt/tomcat/webapps
