---
- name: this is httpd ansible playbook
  hosts: all
  become_user: root
  become: true
  
  tasks:
  
    - name: install httpd
      yum: name=httpd state=latest

    - name: copy index.html
      copy: src=index.html dest=/var/www/html
      notify:
      - restart httpd

    - name: start and enable httpd service
      service: name=httpd state=started enabled=yes

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted 

